spring.application.name=routing-service
server.port=8082
provider-service.base-url=http://localhost:8083
provider-service.timeout-ms=5000
eureka.client.enabled=false
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.com.nexusai.routing_service=INFO