spring.application.name=service-registry

server.port=8761

# Eureka Server Configuration
eureka.instance.hostname=localhost

# Disable client registration (this is the server, not a client)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


# Disable Eureka Server protected mode for development
eureka.server.enable-self-preservation=false

# Log settings
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF